version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "596059741778"
    CLUSTER: "demo"
    SERVICE: "appnode"
    IMAGE_REPO_NAME: "appnode"
    IMAGE_TAG: 1
    #AWS_DEFAULT_REGION: "us-east-1"
    
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin 596059741778.dkr.ecr.us-east-1.amazonaws.com/appnode
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker build -t 596059741778.dkr.ecr.us-east-1.amazonaws.com/appnode:latest .
      - echo Copiando imagen de Docker a repositorio...
      - docker tag $IMAGE_REPO_NAME:latest 596059741778.dkr.ecr.us-east-1.amazonaws.com/appnode:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      #- docker push 596059741778.dkr.ecr.us-east-1.amazonaws.com/appnode:$IMAGE_TAG
      - aws ecs update-service --cluster $CLUSTER --service $SERVICE  --force-new-deployment
artifacts:
  files: 
    - imageDetail.json
    - appspec.yml
    - taskdef.json
